[project]
name = "python-assesment"
version = "0.1"

dependencies = [
    "starlette", # NOTE: Asgi Web framework
    "hypercorn", # NOTE: async webserver
    "pydantic", # NOTE: not used yet...
    "scalar-fastapi" # NOTE: OpenAPI(3.0) Web Interface
]
